### ISSUE TITLE
[[Construct]] seems wrong

### ISSUE THREAD

**Issue by Loirooriol** [isiahmeadows/function-composition-proposal#2]
You defined the composed function to behave like

```js
function compose(f, g) {
  if (typeof f !== "function") throw new TypeError("Expected `f` to be a function");
  if (typeof g !== "function") throw new TypeError("Expected `g` to be a function");
  return Object.defineProperty(function () {
    return new.target != null ? g(new f(...arguments)) : g(f(...arguments));
  }, "length", {value: f.length});
}
```

But I don't like how [[Construct]] behaves. [[Construct]] must always return an object, but `g` is not informed at all that its returned value will be replaced by an object if it's primitive.

I think it would be less confusing if composed functions weren't constructors, i.e.

```js
function compose(f, g) {
  if (typeof f !== "function") throw new TypeError("Expected `f` to be a function");
  if (typeof g !== "function") throw new TypeError("Expected `g` to be a function");
  return Object.defineProperty(() => g(f(...arguments)), "length", {value: f.length});
}
```

Alternatively, the instantiated function could be `g` instead of `f`:

```js
function isConstructor(v){try{v=new new Proxy(v,{construct:()=>[]})}catch(e){v=0}return !!v}
function compose(f, g) {
  if (typeof f !== "function") throw new TypeError("Expected `f` to be a function");
  if (typeof g !== "function") throw new TypeError("Expected `g` to be a function");
  if (!isConstructor(g)) {
    return Object.defineProperty(() => g(f(...arguments)), "length", {value: f.length});
  }
  let composed = (0, function () {
    let r = f(...arguments);
    return new.target ? Reflect.construct(g, [r], new.target) : g(r);
  });
  return Object.defineProperties(composed, {
    "length": {value: f.length},
    "prototype": {value: Object.create(g.prototype, {
      constructor: {writable: true, configurable: true, value: composed}
    })}
  });
}
```

This would allow composed functions to be meaningfully subclassable.

**Comment by isiahmeadows** [comment]
I've made a few adjustments to [that section](https://github.com/isiahmeadows/function-composition-proposal#proposed-syntaxsemantics) of my proposal, and made it a little higher-level, so it's a little clearer what it actually expects.

**Comment by Loirooriol** [comment]
Still same problem. `g` is called instead of instantiated, so it doesn't know that it is expected to return an object. And if you don't use `Reflect.construct`, subclassing the composed function won't work as one would expect.

**Comment by isiahmeadows** [comment]
@Loirooriol That section isn't supposed to be exact, and I'd rather avoid prematurely nailing down subtler semantics like subclassing. I did fix the code to use `Reflect.construct` and `Reflect.apply` to better emphasize the forwarding I meant.

As for constructing *g* instead of calling it, I disagree. Here's how composition is meant to work:

1. Invoke the first function the same way the composed function was called. If it was constructed, construct the function. If it was called called, call the function. All the internal variables are likewise forwarded.
2. Pipe the result through the rest of the functions with all of their `this` values being set to the current instance.

By "current instance", I take it a little loosely:

- If the first function was constructed, its result is also the current instance, because that's the closest we'll get to a meaningful `this` value.
- Otherwise, the current instance is literally whatever happens to be passed as `this`.

**Comment by Loirooriol** [comment]
If `compose(f, g)(...args)` means `g(f(...args))`, then I expected `new compose(f, g)(...args)` to be `new g(f(...args))`. Like this:

```js
class Monster { constructor(legs) { this.legs = legs; } }
let BigMonster = compose(n => 2*n, Monster);
new BigMonster(4).legs; // 8
```

But you seem to prefer things like

```js
let FrozenArray = compose(Array, Object.freeze);
let arr = new FrozenArray(1,2,3); // [1,2,3]
Object.isFrozen(arr); // true
```

If you go this way, then if `g` does not return an object, you should return the instance created by `f`. Otherwise you will only get an empty object which inherits from the prototype of the composed function.

```js
function compose(f, g) {
  if (typeof f !== "function") throw new TypeError("Expected `f` to be a function");
  if (typeof g !== "function") throw new TypeError("Expected `g` to be a function");
  return function () {
    if (new.target != null) {
      var inst = Reflect.construct(f, arguments, new.target)
      var ret = g.call(inst, inst);
      return Object(ret) === ret ? ret : inst;
    } else {
      return g.call(this, Reflect.apply(f, this, arguments))
    }
  };
}
```

**Comment by isiahmeadows** [comment]
@Loirooriol You are correct, in that I'm envisioning stuff like `let FrozenArray = Array :> Object.freeze`, rather than `let BigMonster = (x => x * 2) :> Monster`. I think I see where our brains are differing:

- You think of transforming the arguments you will eventually construct with.
- I think of transforming the result after creating the object.

> If you go this way, then if g does not return an object, you should return the instance created by f. Otherwise you will only get an empty object which inherits from the prototype of the composed function.

That was implied in the "mod a few nuances" phrase above my pseudo-implementation snippet. I wanted to be clear on the intent, without getting noisy with the details.

-----

In all honesty, I'm just going to ditch the constructor end altogether, because it's starting to seem futile to actually make it into something consistent.
